name: hipparchus

channels:
    - astropy
    - conda-forge

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - sphinx-astropy
    - numpy
    - scipy
#    - pip:
#        - numpy
#        - scipy
