name: hipparchus

channels:
    - astropy

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - scipy
#   - pip:
#       - dependency_from_pip
